### ISSUE TITLE
Start website locally

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#100]
Is there an easy way to start the website locally? There doesn't seem to be a script that does it.

It's also quite difficult to just start a local server because all paths in the website itself are prefixed with "/eslint-plugin-regexp/". Removing that prefix will cause Vue to generate different _absolute_ paths. This enables me that start the website locally but it will break the live website.

**Comment by ota-meshi** [comment]
Thank you for this question!
You can check the website locally by following the steps below.

1. Build the TS files with `npm run build`.
1. Starts the document dev server with `npm run docs:watch`.
1. Open `http://localhost:8080/eslint-plugin-regexp/`. You can check the document site.

**Comment by RunDevelopment** [comment]
So it was that easy :)

I'll make a PR to add that to the README.
