### ISSUE TITLE
`regexp/no-octal` allows some octal escapes

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#102]
Why does `regexp/no-octal` allow octal escapes that do not start with a `0`? These octal escapes are especially harmful because they look like backreferences. 

In fact, whether `\2` is an octal escape or a backreference depends on the number of capturing groups in the pattern. This is a big problem because this means that adding capturing groups might change some octal escapes into backreferences. Similarly, removing capturing group might leave backreferences that are now interpreted as octal escapes.

**Comment by ota-meshi** [comment]
> These octal escapes are especially harmful because they look like backreferences.

Right.
The purpose of the rule when I created this rule was to avoid misinterpreting the wrong number after `\0` .
I think we need to change the `no-octal` rule to check all cases.

**Comment by RunDevelopment** [comment]
> I think we need to change the `no-octal` rule to check all cases.

I'll make a PR.
