### ISSUE TITLE
Consistent formatting in messages

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#106]
I noticed that regex expressions are quoted inconsistently. Sometime [single quotes](https://github.com/ota-meshi/eslint-plugin-regexp/blob/9b0a1f93edae35ae388e93b0eaa0bdcf68c389a6/lib/rules/negation.ts#L26) are used and sometimes [double quotes](https://github.com/ota-meshi/eslint-plugin-regexp/blob/9b0a1f93edae35ae388e93b0eaa0bdcf68c389a6/lib/rules/no-dupe-characters-character-class.ts#L261) are used. We should use one quoting style consistently instead.

([This rule](https://github.com/ota-meshi/eslint-plugin-regexp/blob/9b0a1f93edae35ae388e93b0eaa0bdcf68c389a6/lib/rules/prefer-regexp-test.ts#L23) even uses backticks but not for regexes.)

Which quoting style do we want? Single, double, or backticks?

**Comment by ota-meshi** [comment]
Thank you for this issue!
ESLint seems to use a lot of single quotes, so I think it's better to use single quotes.


Script used for checking:

```ts
import { Linter } from "eslint"

const counts: Record<string, number> = {}
for (const [, rule] of new Linter().getRules()) {
    for (const message of Object.values(rule.meta?.messages ?? {})) {
        if (message.includes('"')) {
            counts['"'] = (counts['"'] ?? 0) + 1
        }
        if (message.includes("`")) {
            counts["`"] = (counts["`"] ?? 0) + 1
        }
        if (message.includes("'")) {
            counts["'"] = (counts["'"] ?? 0) + 1
        }
    }
}
console.log(counts) // { "'": 211, '`': 17, '"': 6 }
```
