### ISSUE TITLE
`no-octal`: Provide suggestions

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#115]
Maybe we could [provide a suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) to replace an octal escape with a hexadecimal escape (e.g. `\04` -> `\x04`)?

We can't apply fixes automatically for this rule but we can suggest a fix the user can apply themself.

**Comment by ota-meshi** [comment]
Sounds good to me!
