### ISSUE TITLE
`prefer-regexp-test` doesn't account for non-RegExp arguments

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#119]
The `String.prototype.match` function [allows non-RegExp arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#a_non-regexp_object_as_the_parameter) which isn't accounted for. This causes incorrect auto fixes.

For more information, see sindresorhus/eslint-plugin-unicorn#1150.

**Comment by ota-meshi** [comment]
I didn't know that 😓.  I will fix it.
