### ISSUE TITLE
Refactoring `defineRegexpVisitor(context,{createVisitor})`

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#149]
Change the argument of createVisitor to context only.

See https://github.com/ota-meshi/eslint-plugin-regexp/pull/148#issuecomment-821915380

We also need to consider whether we can add other helper functions. e.g. `getRegexpLocation()`

**Comment by RunDevelopment** [comment]
> We also need to consider whether we can add other helper functions. e.g. `getRegexpLocation()`

I like that. We could also supply functions to create fixes. This will make them more convenient to use.
