### ISSUE TITLE
Release v0.9.0

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#160]
I plan to release the minor version about once every two weeks.
However, this plugin repository has already incorporated many changes since v0.8.0. https://github.com/ota-meshi/eslint-plugin-regexp/compare/v0.8.0...master
So it hasn't been long since the release of v0.8.0, but I would like to release v0.9.0.
@RunDevelopment  Could you let me know if you think it's okay to release v0.9.0?

**Comment by RunDevelopment** [comment]
> let me know if you think it's okay to release v0.9.0?

Sure! I don't see any reason not to publish a new version.
