### ISSUE TITLE
New rule to enforce consistent hex escape

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#162]
Characters that can use hexadecimal escape can use both hexadecimal escape and unicode escape.
I think it useful to have a new rule that enforces the consistent use of hexadecimal escapes.

Rule Name: `regexp/hexadecimal-escape`
Options:
- `"always"` ... Expects that the hexadecimal escape will be used whenever possible. This is default.
- `"never"` ... Ensures that no hexadecimal escape is used in any characters.

**Comment by ota-meshi** [comment]
Hmm... We may need to be able to choose what to do with control escape.

**Comment by RunDevelopment** [comment]
Great idea!

> We may need to be able to choose what to do with control escape.

Control escapes aren't hexadecimal, so I don't see why they would be relevant for this rule? We only need to care about `\xFF`, `\uFFFF`, and `\u{10FFFF}`, right?
