### ISSUE TITLE
Consistent control escapes

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#165]
As mentioned by @ota-meshi [here](https://github.com/ota-meshi/eslint-plugin-regexp/pull/163#discussion_r616516223):

> [...] we may need another rule to convert it [`\x0a`] to `\n`.

I want to add that we could make a rule to consistently escape control characters. 

We already have `prefer-t` which does exactly this for `\t`. We should probably deprecate `prefer-t` in favor of a more general rule that handles `\t`, `\r`, `\n`, and `\f`.

(The rule should also be aware of rules like `no-obscure-range`, so we don't have two rules fighting each other.)

**Comment by ota-meshi** [comment]
I think it's a good idea to deprecate the `prefer-t` rule 👍

**Comment by ota-meshi** [comment]
I will work on this rule.

**Comment by RunDevelopment** [comment]
Sorry but I already do :)

**Comment by RunDevelopment** [comment]
I should have said that. Sorry.
