### ISSUE TITLE
Detect partial patterns

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#181]
Discussion [here](https://github.com/ota-meshi/eslint-plugin-regexp/pull/179#issuecomment-826308528).

**Comment by RunDevelopment** [comment]
I'll review the PR shortly.

> Do you think the `allowTop` option of the `no-useless-non-capturing-group` rule should be changed to ignore only partial patterns? 

I think `allowTop` should have 3 states:

1. `true | "always"`: Always allow top-level groups (partial or not)
2. `false | "never"`: Never allow top-level groups (partial or not)
3. `"partial"` (_default_): Only allow top-level groups in partial patterns.

> Do you think we should check partial patterns for other rules as well?

Yes. `no-lazy-ends` also has a problem with partial patterns. But I think those 3 rules are the only ones that have to account for partial patterns.

**Comment by ota-meshi** [comment]
I opened two PRs. #215, #216

If we can merge both, I think we can close this issue.

**Comment by RunDevelopment** [comment]
Thank you @ota-meshi!

**Comment by RunDevelopment** [comment]
Thanks to your awesome work @ota-meshi, we can now close this issue.
