### ISSUE TITLE
Categorize rules

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#198]
The list of supported rules is getting long (56 rules) and will only get longer in the future. 

I think we should categorize our rules so our users can quickly find rules with somewhat similar functionality.

For now, I think the categories "Possible Errors", "Best Practices", and "Stylistic Issues" (taken from the ESLint website) might be a good fit.

@ota-meshi What do you think about this?

**Comment by ota-meshi** [comment]
I agree with you:+1:.

I want to add a field for `meta.docs.category` to each rule and change it so that it is automatically categorized on the document.
