### ISSUE TITLE
Support ES2022 RegExp Match Indices (d flag)

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#217]
RegExp match indices has reached stage-4.

tc39/proposals@f0adbe1
https://github.com/tc39/proposal-regexp-match-indices

The standard eslint parser still cannot parse the d flag, but this plugin should support the d flag if needed.
https://github.com/eslint/eslint/issues/14640

**Comment by RunDevelopment** [comment]
A quick summary of what we have to do:

- [ ] Update regexpp version (mysticatea/regexpp#22)
    Thank you @ota-meshi for the PR!
- [ ] Update regexp-ast-analysis version
    This contains the type we use to represent flags. I just released a new version that supports the `d` flag.
- [ ] Update refa version (RunDevelopment/refa#32)
    This is optional. I made the PR but it won't do much for us. refa's RegExp parser converts capturing groups into non-capturing groups anyway.
