### ISSUE TITLE
Add auto-fix for `no-unused-capturing-group`?

### ISSUE THREAD

**Issue by fisker** [ota-meshi/eslint-plugin-regexp#230]
Let's insert `?:`?

**Comment by ota-meshi** [comment]
Thank you for posting the issue!

The report may have misused the regular expression, so I think it should be a suggestion instead of an auto-fix.

**Comment by fisker** [comment]
I'm not by convinced by "misused", is there any case that insert `?:` will result differently?

**Comment by fisker** [comment]
Expect backreferences numbers after it.

**Comment by ota-meshi** [comment]
For example, the following program is an example of using the wrong index.
This source code needs to shift the index instead of inserting the `?:`.

```diff
'2000-12-31'.replace(/(\d{4})-(\d{2})-(\d{2})/, (y, m, d) => `${y}/${m}/${d}`); // "2000-12-31/2000/12"
'2000-12-31'.replace(/(\d{4})-(\d{2})-(\d{2})/, (_, y, m, d) => `${y}/${m}/${d}`); // "2000/12/31"
```

**Comment by RunDevelopment** [comment]
> I'm not by convinced by "misused", is there any case that insert `?:` will result differently?
> Expect backreferences numbers after it.

Yes.

```js
var replaced = '2000-12-31'.replace(/(\d{4})-(\d{2})-(\d{2})/, '$3') // "2000/12"
```

![image](https://user-images.githubusercontent.com/20878432/120887651-70cb5d00-c5f4-11eb-840e-f65a24cd2d71.png)

But this issue can be solved by only fixing a capturing group if it is the last capturing group in the regex.

---

That being said, I also agree with @ota-meshi that unused capturing groups indicate a potential problem. Auto fixes should only be used where it is at least 99% clear what the correct code is. Suggestions are the right tool here IMO.

**Comment by fisker** [comment]
Cases you mentioned all the same as I said. It will effect groups indexes. At least in `.test()` if there are no indexed backreferences after the unused group, safe to fix.
