### ISSUE TITLE
Tasks for release v1.0.0.

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#239]
I think we have almost done all the work needed to release v1.0.0 :tada:

@RunDevelopment
I think the next release could be v1.0.0, what do you think?

[Milestone v1.0](https://github.com/ota-meshi/eslint-plugin-regexp/milestone/1)

**Comment by RunDevelopment** [comment]
I agree. Let's make the next release v1.0.0.

I will do some testing today and this weekend and try to find some more bugs and rough edges.

**Comment by RunDevelopment** [comment]
@ota-meshi Seems like we're getting close to v1.0.0. I think we will be ready to release after the open PRs are merged and #291 is dealt with.

**Comment by ota-meshi** [comment]
@RunDevelopment  I agree with you:tada:
After all PR and #291 have been resolved, I will release 1.0 when I have time.

**Comment by ota-meshi** [comment]
I have just released eslint-plugin-regexp v1.0.0🎉
https://github.com/ota-meshi/eslint-plugin-regexp/releases/tag/v1.0.0

**Comment by RunDevelopment** [comment]
🎉
