### ISSUE TITLE
Suggestion: add an `all` configuration

### ISSUE THREAD

**Issue by darkred** [ota-meshi/eslint-plugin-regexp#247]
Currently, the only configuration available is `recommended` ([see](https://github.com/ota-meshi/eslint-plugin-regexp/tree/master/lib/configs)). 
_The alternative the user has is to manually configure the rules he wants._

My suggestion is to offer an additional `all` configuration.

For reference, ESLint itself offers both [`recommended`](https://eslint.org/docs/user-guide/configuring/configuration-files#using-eslintrecommended) and [`all`](https://eslint.org/docs/user-guide/configuring/configuration-files#using-eslintall) ([see](https://github.com/eslint/eslint/tree/master/conf)) configuration:

<details>
<summary>Notes from documentation:</summary>

Use `"eslint:recommended"` to enables a subset of core rules that report common problems.

Use `"eslint:all"` to enable all core rules in the currently installed version of ESLint. The set of core rules can change at any minor or major version of ESLint.
> Important: This configuration is not recommended for production use because it changes with every minor and major version of ESLint. Use it at your own risk.
</details>

With the active development taking place for this plugin and the wide range of rules,
I believe it would be useful for the user to be able to try the `all` configuration on his project, 
to see which more rules he would like to enable.

**Comment by darkred** [comment]
If you agree with my suggestion, I'd gladly provide a PR (I already have the changes).

**Comment by RunDevelopment** [comment]
This might be a good way for people to test out the plugin. 

But we have to clearly communicate that this config is only intended for testing. As ESLint says: "it changes with every minor and major version". Same for our `all` config.

@ota-meshi What do you think?

**Comment by ota-meshi** [comment]
It sounds good to me:+1:

**Comment by darkred** [comment]
I made PR #250 .
