### ISSUE TITLE
Feature request: Browsre compatibility rule

### ISSUE THREAD

**Issue by ilyub** [ota-meshi/eslint-plugin-regexp#272]
Hello,

Thank you for the plugn.

Do you have rules to disallow features based on browser support?

For example:
https://caniuse.com/?search=RegExp%3A%20lookbehind
Lookbehind is not supported by some modern browser. So, it would be good to have a rule that disallows this feature alltogether.

**Comment by RunDevelopment** [comment]
Do we really need a new rule for that? Couldn't you just use `"parserOptions": { "ecmaVersion": 2017 }`?

**Comment by ilyub** [comment]
ecmaVersion does not work with typescript parser and typescript does not transpile regexps.

However, I found this discussion:
https://stackoverflow.com/questions/63792948/typescript-eslint-parser-parseroptions-ecmaversion-ignored-not-linting
that refers to eslint-plugin-es.

eslint-plugin-es already have the necessary compatibility check.

So, new rule is really not needed.

Thx for your work.
