### ISSUE TITLE
Change rules to use `mention` function.

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#291]
https://github.com/ota-meshi/eslint-plugin-regexp/pull/289#issue-707704284

We need to know which rules need to be changed.

**Comment by RunDevelopment** [comment]
I think pretty much all rules that include parts of the pattern (not just single characters) in their messages need to be changed since the included part may contain control characters.

It shouldn't be difficult to make that change. If you agree, I'll make a PR.

**Comment by ota-meshi** [comment]
> It shouldn't be difficult to make that change.

Oh really. Please open the PR.
