### ISSUE TITLE
Report and fix confusing quantifiers around assertions

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#309]
**Description**
Assertions can be used to force certain quantifiers (or alternatives) to be entered. 

E.g. in `a\b-?a`, the `\b` forces `-?` to be entered. The quantifier is useless in this case. 
`a\b-?a` ==<sub>this issue</sub> `a\b-a` ==<sub>no-useless-assertions</sub> `a-a`.

We need to check all quantifiers with a minimum of 0 that are next to an assertion. If the assertion forces us to enter the quantifier, then the minimum should be 1 instead.

---

I think this should be part of `regexp/confusing-quantifier` but I'm not certain. What do you think @ota-meshi?

**Comment by ota-meshi** [comment]
> I think this should be part of regexp/confusing-quantifier

I agree with you :+1:

**Comment by RunDevelopment** [comment]
While trying to implement this, I noticed we could make a more general and more useful rule out of this.

The idea is the same: Assertions can be used to force the regex engine to enter (or not to enter) certain alternatives or quantifiers.

E.g. in `a\b-?a`, the `\b` forces `-?` to be entered. In `a\b(a|-)`, the `\b` forces the `-` alternative to be entered. In `a\ba*-`, the `\b` forces `a*` to be not be entered (`a*` in useless).

This new rule is similar to `no-useless-assertions`. While no `no-useless-assertions` tries to find useless assertions based on the rest of the pattern, the new rule tries to find useless parts of the pattern based on assertions. They also overlap because an assertion that always rejects because of the pattern also makes the pattern useless, so we have to pay attention to that.

Also, I'm not sure what to call the new rule. `no-useless-asserted` maybe?

**Comment by ota-meshi** [comment]
> While trying to implement this, I noticed we could make a more general and more useful rule out of this.
> The idea is the same: Assertions can be used to force the regex engine to enter (or not to enter) certain alternatives or quantifiers.

I think that's a great idea!

> Also, I'm not sure what to call the new rule. no-useless-asserted maybe?

How about naming it `no-contradiction-with-assertion`?

**Comment by RunDevelopment** [comment]
> How about naming it `no-contradiction-with-assertion`?

I like that name. Let's go with taht.
