### ISSUE TITLE
Which `toCharSet` should we use going forward?

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#322]
The reason we added `RegexpContext.toCharSet` was performance (see #148). Since #317, this is no longer a problem. All character-related `regexp-ast-analysis` functions are now cached automatically.

This leaves us in a kinda awkward situation: Which `toCharSet` should we use?

Also, shouldn't we remove [this rule](https://github.com/ota-meshi/eslint-plugin-regexp/blob/750abbc41b66e6ae49fb8531bf7997129254cdba/.eslintrc.js#L45)?

@ota-meshi

**Comment by ota-meshi** [comment]
I think we should use `regexp-ast-analysis.toCharSet` :+1:.
