### ISSUE TITLE
Bring over all of ESLint's regex rules

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#325]
ESLint has a few really good rules for regexes (e.g. [`no-misleading-character-class`](https://eslint.org/docs/rules/no-misleading-character-class)). We have already brought over some of them and I wonder whether we should bring over the rest as well? We have more precise error reporting (better user experience) and can handle complex `RegExp` constructors better (more error reports), so our users would benefit from that.

Consensus: Yes, let's bring them all over.

- [x] [`no-control-regex`](https://eslint.org/docs/rules/no-control-regex)
  #333
- [x] [`no-div-regex`](https://eslint.org/docs/rules/no-div-regex) (not necessary)
- [x] [`no-empty-character-class`](https://eslint.org/docs/rules/no-empty-character-class)  
  #329
- [x] [`no-invalid-regexp`](https://eslint.org/docs/rules/no-invalid-regexp)
- [x] [`no-misleading-character-class`](https://eslint.org/docs/rules/no-misleading-character-class) 
  #332
- [x] [`no-regex-spaces`](https://eslint.org/docs/rules/no-regex-spaces) (subset of `regexp/perfer-quantifier`)
- [x] [`no-useless-backreference`](https://eslint.org/docs/rules/no-useless-backreference)
- [x] [`prefer-named-capture-group`](https://eslint.org/docs/rules/prefer-named-capture-group)
  #330 
- [x] [`prefer-regex-literals`](https://eslint.org/docs/rules/prefer-regex-literals) (?)
- [x] [`require-unicode-regexp`](https://eslint.org/docs/rules/require-unicode-regexp)
  #331 

Regarding `prefer-regex-literals`: I don't think that we can improve this rule, so we don't need to bring it over.

**Comment by ota-meshi** [comment]
I think it's good to implement the regex related rules of ESLint as the rules of this plugin.
I think it benefits users, as you say.

**Comment by ota-meshi** [comment]
`no-div-regex` rule reports regex that looks like division. It may be possible to improve the reporting position, but I think it is also possible with the ESLint's rule. So I don't think it's necessary to move to this plugin.

**Comment by RunDevelopment** [comment]
I want to do `no-misleading-character-class`. I'll make it fixable using the string semantics from [this proposal](https://github.com/tc39/proposal-regexp-set-notation#whats-the-match-order-for-character-classes-containing-strings).

**Comment by RunDevelopment** [comment]
Now that I think about it: these characters with multiple code points also cause problems with quantifiers. E.g.:

![image](https://user-images.githubusercontent.com/20878432/133888931-44d724b0-21af-4f34-b776-091957ad174c.png)

I kinda don't want to have a separate rule `no-misleading-quantifier` because that sounds like `no-confusing-quantifier` which is very different.

Maybe we could make a new rule `no-misleading-multi-code-point-characters` (needs a better name) or should there be two different rules and we just need a better name for `no-misleading-quantifier`?

**Comment by RunDevelopment** [comment]
Regarding `no-regex-spaces`:
I don't think we need it because `regexp/perfer-quantifier` is a superset of it. This is obvious from [its tests](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-regex-spaces.js). The rules only differ in that `perfer-quantifier` also considers escaped spaces (e.g. `\x20`, `\ `) when making a quantifier while `no-regex-spaces` only allows literal spaces.

**Comment by ota-meshi** [comment]
> Maybe we could make a new rule no-misleading-multi-code-point-characters

I think the `no-misleading-multi-code-point-characters` rule is great :+1:

**Comment by RunDevelopment** [comment]
I'll make it but I'll call it `no-misleading-unicode-character` instead. Maybe a tad too general but also catchier.

**Comment by ota-meshi** [comment]
Now that we have implemented all the planned rules :tada:, I close this issue.
