### ISSUE TITLE
`sort-flags` should autofix flags that's a string literal

### ISSUE THREAD

**Issue by fisker** [ota-meshi/eslint-plugin-regexp#337]
**Information:**
- ESLint version: 7.32.0
- `eslint-plugin-regexp` version: 1.3.0

**Description**

`/a/us` is fixable, but `RegExp('a', 'us')` is not.

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
However, the [DEMO] does not reproduce the problem.


![image](https://user-images.githubusercontent.com/16508807/134800237-a95f11cf-c42d-42bb-9751-71bb111e4790.png)


Would you please provide more detailed information?

[DEMO]: https://ota-meshi.github.io/eslint-plugin-regexp/playground/#eJyrVkrOT0lVslLST9QvLbaOyQtKTXetKNBQT1TXUVAvLVbXtFbSUSoqzUktVrKqVipKTU+tKNAvzi8q0U3LSUwHChrV1gIA7vwWQw==

**Comment by fisker** [comment]
Ah. I simplified the example too much...  [Here](https://ota-meshi.github.io/eslint-plugin-regexp/playground/#eJyrVkrOT0lVslIKSk13rSjQUE9UV9BWSNJRUC8tVte0VtJRKirNSS1WsqpWKkpNT60o0C/OLyrRTctJTAcKGtXWAgB92BRk)

**Comment by RunDevelopment** [comment]
Right now, `sort-flags` requires the whole pattern to be owned (= we can statically know and change it). This requirement isn't actually necessary, so let's remove it.
