### ISSUE TITLE
`regexp/prefer-d`: Add an option for whole `\d`s

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#341]
**Description**
I think that the range `0-9` can be more readable than `\d` in some situations. E.g. `[0-9a-f]` vs `[\da-f]`.

I think we should an option that makes it so that only whole character classes that are equal to `\d` or `\D` are reported. So `[0-9]` will be reported but `[0-9a-f]` won't.

What do you think @ota-meshi?

**Comment by ota-meshi** [comment]
I personally think that worth this rule to unify those writing styles.

If we add an option to allow `[0-9a-f]` to the rule, I think the rule should report `[\da-f]`.
