### ISSUE TITLE
Further explanation for `no-unused-capturing-group`

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#346]
I coincidentally found stylelint/eslint-config-stylelint#141 today and I thought that the discussion around `no-unused-capturing-group` was interesting.

In the documentation of `no-unused-capturing-group`, we say that non-capturing groups should be used to "optimize regular expressions" (as in "improve performance") but I don't think that's the only reason non-capturing groups should be preferred. 

Using non-capturing groups also communicates intend more clearly. A capturing group is similar to a variable in that its value (the captured text) is stored and can be accessed, and like with variables, unused capturing groups are code smell. If a regex contains a capturing group, then I'll expect its captured text to be used in some form or another.

If it's alright with you @ota-meshi, then I'll add this reasoning to the documentation.

**Comment by ota-meshi** [comment]
I think it's good for people to add it to the documentation :+1:. I think that not many people (including me) are familiar with regexp best practices.

**Comment by RunDevelopment** [comment]
> I think that not many people (including me) are familiar with regexp best practices.

Neither am I. Those were just my thoughts on unused capturing groups.

**Comment by ota-meshi** [comment]
I think your thoughts are true! I think we need to add it to the documentation
