### ISSUE TITLE
Rule proposal: `no-missing-g-flag`

### ISSUE THREAD

**Issue by fisker** [ota-meshi/eslint-plugin-regexp#472]
**Motivation**

When calling [`String#replaceAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) and [`String#matchAll()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) with non-global RegExp, it will be a runtime error. I hope to catch this pattern during linting.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#exceptions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#exceptions

**Description**

Forbid calling `String#replaceAll()` or `String#matchAll()` with non-global pattern.

**Examples**

```js
/* ✓ GOOD */
foo.replaceAll(" ", '')
foo.replaceAll(/\s/g, '')
foo.matchAll(/\s/g)

/* ✗ BAD */
foo.replaceAll(/\s/, '')
foo.matchAll(/\s/)
```

**Comment by ota-meshi** [comment]
Thank you for the rule suggestions! That rule sounds good to me!
