### ISSUE TITLE
`regexp/use-ignore-case` changes matched strings with Unicode

### ISSUE THREAD

**Issue by kevinoid** [ota-meshi/eslint-plugin-regexp#546]
**Information:**
- ESLint version: 8.46.0
- `eslint-plugin-regexp` version: 1.15.0

**Description**

The [`regexp/use-ignore-case`](https://ota-meshi.github.io/eslint-plugin-regexp/rules/use-ignore-case.html) rule added by #345 to resolve #201 suggests using the `i` flag to simplify expressions.  Unfortunately, when the `u` or `v` flag is used, it may also change the set of strings matched by the expression.  For example, `/[A-Za-z]/u` differs from `/[a-z]/iu` when matching `'\u{212A}'`.  This difference may be exacerbated by [`regexp/require-unicode-regexp`](https://ota-meshi.github.io/eslint-plugin-regexp/rules/require-unicode-regexp.html) if users naively add both flags.

Perhaps it would make sense to (optionally) exclude Unicode regexes from this rule?

Thanks for considering,
Kevin

**Comment by RunDevelopment** [comment]
> For example, `/[A-Za-z]/u` differs from `/[a-z]/iu` when matching `'\u{212A}'`.

Yes, this is true, but `regexp/use-ignore-case` knows about this and doesn't suggest anything in this case. This can be seen on [our playground](https://ota-meshi.github.io/eslint-plugin-regexp/playground/#MTIwLDE1NiwxNzEsODYsNzQsMjA2LDc5LDczLDg1LDE3OCw4Miw3NCwyMDMsMjA3LDg3LDE3Niw4NSwyMDgsMTQzLDExOCwyMTIsMTQxLDc0LDIxMiwxNzMsMTM4LDIxMywxNDMsMjAxLDY3LDIzLDIwMSwxOTYsMjAsNDIsODUsMTcwLDUsMCwxMzYsMTczLDE5LDE4OQ==) as well:
![image](https://github.com/ota-meshi/eslint-plugin-regexp/assets/20878432/a7868314-19bb-4f00-85d8-599c881b2de5)

So it seems to me that `regexp/use-ignore-case` behaves correctly, at least for this example.

**Comment by kevinoid** [comment]
You're right!  I could have sworn `regexp/use-ignore-case` suggested changing such an expression, but I'm unable to reproduce it now.  I must have been misunderstanding something.  Sorry for the noise.  Thanks for setting me straight.
