### ISSUE TITLE
Sort string alternatives

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#572]
The order of string alternatives (e.g. `\q{foo|bar}`) does not matter, so it would be nice if they could automatically be sorted. The semantics and functionality should be the same as [`sort-alternatives`](https://ota-meshi.github.io/eslint-plugin-regexp/rules/sort-alternatives.html). 

I'm not sure whether sorting string alternatives should be a new rule or whether it should be part of `sort-alterantives`.

**Comment by ota-meshi** [comment]
Good idea!
In my opinion, it's a feature included in sort-alternatives rule.
