### ISSUE TITLE
Disable `require-jsdoc` rule?

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#577]
I would like to disable the `require-jsdoc` ESLint rule. I don't like this rule, because it encourages code like this:

```ts
/** Extract property references from the given pattern */
export function* extractPropertyReferencesForPattern(
    node: Pattern,
    context: Rule.RuleContext,
): Iterable<PropertyReference> {
    yield* iteratePropertyReferencesForPattern(node, context)
}
```

What is the point of having a JSDoc comment when the comment is just the function name + arguments restated as a sentence? These JSDoc comments do not add information. Reading them is a waste of time, because we can get more information by looking at the function signature.

We all agree that littering our code with comments like this is bad:

```ts
// decrement i
i--
```

So why do we have an ESLint rule that encourages the JSDoc equivalent of this? 

---

So yeah. That's why I would like to disable this rule. I would also like to remove the ~200 useless doc comments scattered throughout the entire code base. This would likely change almost every file (e.g. just look at the few dozen `/** Create visitor */ function createVisitor`). 

What do you think @ota-meshi?

**Comment by ota-meshi** [comment]
I agree to turn off require-jsdoc rule :+1: Was using the require-jsdoc rule for me. A lot of the code I write is poorly explained, so it helped me get into the habit of writing code explanations more than the downside of leaving a lot of documentation with verbose method names paraphrased.
This project now has a review process, so I don't think the require-jsdoc rule is necessary.
