### ISSUE TITLE
Additional `/` character was added to my character class in autofix

### ISSUE THREAD

**Issue by tylerlaprade** [ota-meshi/eslint-plugin-regexp#692]
**Information:**
- ESLint version: `8.56.0`
- `eslint-plugin-regexp` version: `2.2.0`

**Description**
The recommended rules' autofix changed `/\s|_|-|\.|name|id|\//gi` to `/[\s_\-./]|name|id/gi`. Forgive me if this has some special meaning I'm not aware of, but isn't there an extra `/` character added to the end of my character class?

**Comment by RunDevelopment** [comment]
That's the `\/` at the end of `/\s|_|-|\.|name|id|\//gi`. The rule for merging characters into a character class can reorder alternatives (if it's safe to do so).

**Comment by tylerlaprade** [comment]
Oh I see, thank you!
