### ISSUE TITLE
Can we avoid multiple rules reporting errors for one regular expression?

### ISSUE THREAD

**Issue by btea** [ota-meshi/eslint-plugin-regexp#756]
For example, the regular expression is `/[^a-zA-Z0-9_$]/g`, the following error message will appear after checking.

![image](https://github.com/user-attachments/assets/c5e02807-7244-4ae4-a0a0-5554f3e2686d)

But in fact, as long as I modify it according to the first error prompt, there will be no problem with the following prompts, so I wonder if I can only display the first error message in this case.

**Comment by ota-meshi** [comment]
That is not possible, since it is impossible to know what each rule will report when processing it.

**Comment by zloirock** [comment]
I think that it makes sense to propose to ESLint core something like `/* eslint-disable-plugin %PLUGIN_NAME% */` and `next-line` version.
