### ISSUE TITLE
`match-any` falsely detects character classes that matching no characters as matching all characters

### ISSUE THREAD

**Issue by RunDevelopment** [ota-meshi/eslint-plugin-regexp#85]
Example:

```js
/[^\s\S]/
```

![image](https://user-images.githubusercontent.com/20878432/113203969-fcc7ae00-926c-11eb-9260-17de07283728.png)

The worst thing about this bug is that the rule is auto-fixable.

**Comment by ota-meshi** [comment]
Thank you for posting many issues! I check each issue.
