### ISSUE TITLE
Refactor using "regexp-ast-analysis"

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-regexp#92]
[refa](https://github.com/RunDevelopment/refa) package seems to have many useful utilities for regular expressions.
I think we can remove a lot of code from eslint-plugin-regexp by refactoring with it.

**Comment by ota-meshi** [comment]
Currently, eslint-plugin-regexp has rules that exclude unicode properties (`\p{...}`) from validation.  
(That's because I didn't know how to get the character set contained in the unicode property.)  
I think we can use refa to check the characters contained in unicode properties.

**Comment by RunDevelopment** [comment]
I changed the title to reflect what actually has to be done. regexp-ast-analysis is a lot easier to use than refa for our purposes.

**Comment by ota-meshi** [comment]
🎉
